In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%config InlineBackend.figure_format = 'retina'
sns.set_style('darkgrid')
sns.set_context('poster', font_scale=1)

from time import sleep
from datetime import timedelta, datetime, date
import requests

In [6]:
me = pd.read_csv('../data/portfolio.csv')
me['total_BTC'] = me.units * me.price_BTC

In [7]:
me

    code         asset       units  price_BTC  total_BTC
0    BTC       Bitcoin    0.178391   1.000000   0.178391
1    ETH      Ethereum    0.417248   0.104540   0.043619
2    XRP        Ripple  171.000000   0.000110   0.018810
3    BCH  Bitcoin Cash    0.299500   0.145650   0.043622
4    XLM       Stellar  469.500000   0.000051   0.023780
5    LTC      Litecoin    1.743212   0.017500   0.030506
6    EOS           EOS   19.080000   0.001205   0.022991
7   IOTA          IOTA  103.396000   0.000210   0.021716
8   DASH          Dash    0.130867   0.069410   0.009083
9    XMR        Monero    0.299660   0.028101   0.008421
10   ZEC         Zcash    0.230764   0.039800   0.009184

In [18]:
price_btc = []
price_usd = []
rank = []

for i in me.asset:
    url = 'https://api.coinmarketcap.com/v1/ticker/' + i.lower().replace(' ', '-')
    response = requests.get(url)
    print (i, response.status_code)
    j = response.json()[0]
    sleep(1)
    
    price_btc.append(j['price_btc'])
    price_usd.append(j['price_usd'])
    rank.append(j['rank'])

Bitcoin 200
Ethereum 200
Ripple 200
Bitcoin Cash 200
Stellar 200
Litecoin 200
EOS 200
IOTA 200
Dash 200
Monero 200
Zcash 200

In [31]:
me['current_price_btc'] = price_btc
me['current_price_usd'] = price_usd

me.current_price_btc = me.current_price_btc.astype('float')
me.current_price_usd = me.current_price_usd.astype('float')

me['current_usd_total'] = me.units * me.current_price_usd
me['change'] = (me.current_price_btc - me.price_BTC) / me.price_BTC * 100

me['rank'] = rank
me.set_index('rank', inplace=True)
me.reset_index(inplace=True)

In [32]:
me

,rank,code,asset,units,price_BTC,total_BTC,current_price_btc,current_price_usd,current_usd_total,change
0,1,BTC,Bitcoin,0.178391,1.000000,0.178391,1.000000,10419.000000,1858.659059,0.000000
1,2,ETH,Ethereum,0.417248,0.104540,0.043619,0.108391,1120.290000,467.439120,3.683757
2,3,XRP,Ripple,171.000000,0.000110,0.018810,0.000117,1.208350,206.627850,6.281818
3,4,BCH,Bitcoin Cash,0.299500,0.145650,0.043622,0.150214,1552.550000,464.989268,3.133539
4,8,XLM,Stellar,469.500000,0.000051,0.023780,0.000049,0.509643,239.277388,-2.645607
5,7,LTC,Litecoin,1.743212,0.017500,0.030506,0.016415,169.664000,295.760265,-6.197143
6,9,EOS,EOS,19.080000,0.001205,0.022991,0.001218,12.586400,240.148512,1.061428
7,11,IOTA,IOTA,103.396000,0.000210,0.021716,0.000231,2.384840,246.582917,9.860496
8,12,DASH,Dash,0.130867,0.069410,0.009083,0.069075,713.936000,93.430663,-0.481919
9,13,XMR,Monero,0.299660,0.028101,0.008421,0.028333,292.842000,87.753034,0.827017
10,25,ZEC,Zcash,0.230764,0.039800,0.009184,0.039403,407.254000,93.979562,-0.997236